[build]
  command = "cd client && npm install --legacy-peer-deps && npm run build"
  publish = "client/build"
  base = "."

[build.environment]
  NODE_VERSION = "18"
  REACT_APP_API_URL = "https://lpu-student-marketplace.onrender.com/api"
  REACT_APP_RAZORPAY_KEY_ID = "rzp_test_1234567890"
  GENERATE_SOURCEMAP = "false"
  CI = "false"
  NPM_FLAGS = "--legacy-peer-deps"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
