name: Deploy React App to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        cd client
        npm install --legacy-peer-deps

    - name: Build
      run: |
        cd client
        npm run build
      env:
        REACT_APP_API_URL: https://lpu-student-marketplace.onrender.com/api
        REACT_APP_RAZORPAY_KEY_ID: rzp_test_1234567890
        CI: false
        GENERATE_SOURCEMAP: false

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./client/build
